### ISSUE TITLE
不要把代码放到github并且公开

### ISSUE THREAD

**Issue by LiaoHanwen** [super-franky/CSA-Lab1#1]
朋友, 不要把代码放到github并且公开, 不仅可能有被其他同学看到后抄袭的风险, 也有可能被查重系统检测到.

**Comment by super-franky** [comment]
🌚这是刚开始写全是bug的哈哈哈我还没上传完整的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Liao Hanwen <notifications@github.com>
发送时间: Tuesday, October 22, 2019 1:51:13 AM
收件人: super-franky/CSA-Lab1 <CSA-Lab1@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [super-franky/CSA-Lab1] 不要把代码放到github并且公开 (#1)


朋友, 不要把代码放到github并且公开, 不仅可能有被其他同学看到后抄袭的风险, 也有可能被查重系统检测到.

**Comment by LiaoHanwen** [comment]
没事没事  就是提醒下~  尽早关掉吧~

**Comment by super-franky** [comment]
谢啦~


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Liao Hanwen <notifications@github.com>
发送时间: Tuesday, October 22, 2019 11:34:04 AM
收件人: super-franky/CSA-Lab1 <CSA-Lab1@noreply.github.com>
抄送: super-franky <xuyunzhao1997@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [super-franky/CSA-Lab1] 不要把代码放到github并且公开 (#1)


或者 学生账号可以升级成pro账号的 就可以免费开private的repo了~

―
